export const DEFAULT_CATALOG_LISTING_LIMIT = 100;
export const DEFAULT_PAGINATED_PAGE_SIZE = 15;
export const MAX_CATALOG_PAGE_LIMIT = 1000;
export const MAX_CATALOG_PAGE_LIMIT_DISPLAY = MAX_CATALOG_PAGE_LIMIT.toLocaleString('en-US');
