<svelte:head>
	<title>CLI: Tasting - Purveyors Docs</title>
	<meta
		name="description"
		content="purvey tasting commands: log tasting notes and view flavor profiles."
	/>
</svelte:head>

<article class="space-y-10">
	<header>
		<div class="mb-2 flex items-center gap-2 text-sm text-text-secondary-light">
			<a href="/docs" class="hover:text-text-primary-light">Docs</a>
			<span>/</span>
			<a href="/docs/cli/overview" class="hover:text-text-primary-light">CLI</a>
			<span>/</span>
			<span>Tasting</span>
		</div>
		<h1 class="text-3xl font-bold tracking-tight text-text-primary-light">CLI: Tasting</h1>
		<p class="mt-3 text-lg text-text-secondary-light">
			Log tasting notes for roasted coffees and view AI-generated flavor profiles.
		</p>
	</header>

	<section>
		<h2 class="text-xl font-bold text-text-primary-light">Commands</h2>
		<div class="mt-4 space-y-4">
			<div class="rounded-lg border border-border-light p-5">
				<code class="text-sm font-medium text-text-primary-light"
					>purvey tasting list [--roast-id &lt;id&gt;] [--json]</code
				>
				<p class="mt-2 text-sm text-text-secondary-light">
					List tasting notes. Optionally filter to a specific roast session.
				</p>
			</div>
			<div class="rounded-lg border border-border-light p-5">
				<code class="text-sm font-medium text-text-primary-light"
					>purvey tasting profile --catalog-id &lt;id&gt; [--json]</code
				>
				<p class="mt-2 text-sm text-text-secondary-light">
					View the AI-generated flavor profile matrix for a catalog entry. Returns taste category
					scores (fruity, floral, nutty, chocolatey, etc.) on a 0-10 scale.
				</p>
			</div>
		</div>
	</section>

	<section>
		<h2 class="text-xl font-bold text-text-primary-light">AI Tasting Notes</h2>
		<p class="mt-3 text-text-secondary-light">
			The
			<code class="rounded bg-background-secondary-light px-1 py-0.5 text-xs">ai_tasting_notes</code
			>
			field in the catalog is a normalized matrix generated by an LLM from supplier descriptions. It
			enables consistent cross-supplier comparison and powers the tasting radar chart in the web app.
			The
			<code class="rounded bg-background-secondary-light px-1 py-0.5 text-xs"
				>purvey tasting profile</code
			>
			command surfaces this field in a readable format.
		</p>
	</section>

	<div class="border-t border-border-light pt-6">
		<div class="flex items-center justify-between text-sm">
			<a href="/docs/cli/sales" class="text-background-tertiary-light hover:underline"
				>← CLI: Sales</a
			>
			<a href="/docs/cli/agent-integration" class="text-background-tertiary-light hover:underline"
				>CLI: Agent Integration →</a
			>
		</div>
	</div>
</article>
